spring.application.name=Portfolio-AlvaroLorenzo

# Configuración server
server.port=8090

#Configuración H2
spring.datasource.url=jdbc:h2:mem:xilften
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
# Para que data.sql se ejecute después de crear las tablas
spring.jpa.defer-datasource-initialization=true
# Para activar la ejecución de scripts SQL
spring.sql.init.mode=always
spring.jpa.show-sql=true
# Consola de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false